# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "celagus/ubuntu-jira"
  config.vm.box_version = "0.1.1"
  
  config.vm.network "private_network", ip: "10.20.30.41", mask:"255.255.255.0"
  config.vm.network "forwarded_port", guest: 8080, host: 8000

  config.vm.hostname = "ubuntu-jira.localhost"
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-jira"
    v.memory = "2048"
  end

  config.vm.synced_folder ".", "/vagrant"

end
